kumuluzee:
  name: uniborrow-ads-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-location: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/adsDS
      connection-url: jdbc:postgresql://tyke.db.elephantsql.com/aadbqpud
      username: aadbqpud
      password: Ou8T4ikcVC-NF7nVHL3oIwsF_pJFDQnw
      pool:
        max-size: 1
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: 'http://localhost:2379'
  discovery:
    etcd:
      hosts: 'http://localhost:2379'
    metrics:
      web-instrumentation:
        - name: ads-endpoint
          url-pattern: /v1/ads/*
administration:
  maintenance-mode: false