kumuluzee:
  name: uniborrow-ads-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-location: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/adsDS
      connection-url: jdbc:postgresql://tyke.db.elephantsql.com/aadbqpud
      username: aadbqpud
      password: Ou8T4ikcVC-NF7nVHL3oIwsF_pJFDQnw
      pool:
        max-size: 1
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: 'http://localhost:2379'
  discovery:
    etcd:
      hosts: 'http://localhost:2379'
    metrics:
      web-instrumentation:
        - name: ads-endpoint
          url-pattern: /v1/ads/*
  openapi-mp:
    enabled: true
    servlet:
      mapping: /uniborrow-ads/openapi
    ui:
      enabled: true
      mapping: /uniborrow-ads/openapi/ui
      specification-server: http://35.223.79.242
  dev:
    scan-libraries:
      - ads-models
administration:
  maintenance-mode: false